services:
  discord-aurabot:
    build: .
    container_name: discord-aurabot
    command: "npm run start"
    volumes:
      - /path/.env:/app/.env
      - /path/aura-bot:/app/aura-bot
      - /app/discord-aurabot/node_modules
    logging:
      options:
        max-size: "10m"
        max-file: "2"
